USE eeg_db_random;

CREATE TABLE coherence (     
     coherence_id BIGINT AUTO_INCREMENT PRIMARY KEY,     
     patient_id VARCHAR(50),     
     file_id INT,     
     frequency_band VARCHAR(20) NOT NULL,     
     
     Fp1_Fp2 DOUBLE, Fp1_F3 DOUBLE, Fp1_F4 DOUBLE, Fp1_C3 DOUBLE, Fp1_C4 DOUBLE,     
     Fp1_P3 DOUBLE, Fp1_P4 DOUBLE, Fp1_O1 DOUBLE, Fp1_O2 DOUBLE, Fp1_F7 DOUBLE,     
     Fp1_F8 DOUBLE, Fp1_T3 DOUBLE, Fp1_T4 DOUBLE, Fp1_T5 DOUBLE, Fp1_T6 DOUBLE,     
     Fp1_Fz DOUBLE, Fp1_Pz DOUBLE,     
     
     Fp2_F3 DOUBLE, Fp2_F4 DOUBLE, Fp2_C3 DOUBLE, Fp2_C4 DOUBLE, Fp2_P3 DOUBLE,     
     Fp2_P4 DOUBLE, Fp2_O1 DOUBLE, Fp2_O2 DOUBLE, Fp2_F7 DOUBLE, Fp2_F8 DOUBLE,     
     Fp2_T3 DOUBLE, Fp2_T4 DOUBLE, Fp2_T5 DOUBLE, Fp2_T6 DOUBLE, Fp2_Fz DOUBLE,     
     Fp2_Pz DOUBLE,     
     
     F3_F4 DOUBLE, F3_C3 DOUBLE, F3_C4 DOUBLE, F3_P3 DOUBLE, F3_P4 DOUBLE,     
     F3_O1 DOUBLE, F3_O2 DOUBLE, F3_F7 DOUBLE, F3_F8 DOUBLE, F3_T3 DOUBLE,     
     F3_T4 DOUBLE, F3_T5 DOUBLE, F3_T6 DOUBLE, F3_Fz DOUBLE, F3_Pz DOUBLE,     
     
     F4_C3 DOUBLE, F4_C4 DOUBLE, F4_P3 DOUBLE, F4_P4 DOUBLE, F4_O1 DOUBLE,     
     F4_O2 DOUBLE, F4_F7 DOUBLE, F4_F8 DOUBLE, F4_T3 DOUBLE, F4_T4 DOUBLE,     
     F4_T5 DOUBLE, F4_T6 DOUBLE, F4_Fz DOUBLE, F4_Pz DOUBLE,     
     
     C3_C4 DOUBLE, C3_P3 DOUBLE, C3_P4 DOUBLE, C3_O1 DOUBLE, C3_O2 DOUBLE,     
     C3_F7 DOUBLE, C3_F8 DOUBLE, C3_T3 DOUBLE, C3_T4 DOUBLE, C3_T5 DOUBLE,     
     C3_T6 DOUBLE, C3_Fz DOUBLE, C3_Pz DOUBLE,     
     
     C4_P3 DOUBLE, C4_P4 DOUBLE, C4_O1 DOUBLE, C4_O2 DOUBLE, C4_F7 DOUBLE,     
     C4_F8 DOUBLE, C4_T3 DOUBLE, C4_T4 DOUBLE, C4_T5 DOUBLE, C4_T6 DOUBLE,     
     C4_Fz DOUBLE, C4_Pz DOUBLE,     
     
     P3_P4 DOUBLE, P3_O1 DOUBLE, P3_O2 DOUBLE, P3_F7 DOUBLE, P3_F8 DOUBLE,     
     P3_T3 DOUBLE, P3_T4 DOUBLE, P3_T5 DOUBLE, P3_T6 DOUBLE, P3_Fz DOUBLE,     
     P3_Pz DOUBLE,     
     
     P4_O1 DOUBLE, P4_O2 DOUBLE, P4_F7 DOUBLE, P4_F8 DOUBLE, P4_T3 DOUBLE,     
     P4_T4 DOUBLE, P4_T5 DOUBLE, P4_T6 DOUBLE, P4_Fz DOUBLE, P4_Pz DOUBLE,     
     
     O1_O2 DOUBLE, O1_F7 DOUBLE, O1_F8 DOUBLE, O1_T3 DOUBLE, O1_T4 DOUBLE,     
     O1_T5 DOUBLE, O1_T6 DOUBLE, O1_Fz DOUBLE, O1_Pz DOUBLE,     
     
     O2_F7 DOUBLE, O2_F8 DOUBLE, O2_T3 DOUBLE, O2_T4 DOUBLE, O2_T5 DOUBLE,     
     O2_T6 DOUBLE, O2_Fz DOUBLE, O2_Pz DOUBLE,     
     
     F7_F8 DOUBLE, F7_T3 DOUBLE, F7_T4 DOUBLE, F7_T5 DOUBLE, F7_T6 DOUBLE,     
     F7_Fz DOUBLE, F7_Pz DOUBLE,     
     
     F8_T3 DOUBLE, F8_T4 DOUBLE, F8_T5 DOUBLE, F8_T6 DOUBLE, F8_Fz DOUBLE,     
     F8_Pz DOUBLE,     
     
     T3_T4 DOUBLE, T3_T5 DOUBLE, T3_T6 DOUBLE, T3_Fz DOUBLE, T3_Pz DOUBLE,     
     
     T4_T5 DOUBLE, T4_T6 DOUBLE, T4_Fz DOUBLE, T4_Pz DOUBLE,     
     
     T5_T6 DOUBLE, T5_Fz DOUBLE, T5_Pz DOUBLE,     
     
     T6_Fz DOUBLE, T6_Pz DOUBLE,     
     
     Fz_Pz DOUBLE,     
     
     FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,     
     FOREIGN KEY (file_id) REFERENCES origin_files(file_id) ON DELETE CASCADE,     
     INDEX idx_frequency_band (frequency_band) 
);